repos:
- repo: meta
  hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
# - repo: https://github.com/sirosen/check-jsonschema
#   rev: 0.16.2
#   hooks:
#     - id: check-github-workflows
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      # explicitly pass settings file so that isort does not try to deduce
      # which settings to use based on a file's directory
      args: ["--settings-path", ".isort.cfg"]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      args: [flox/]